# Argo Workflows v4 on GKE Autopilot
server:
  extraArgs:
    - --auth-mode=server
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  workflowNamespaces:
    - null-realm-agents
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

useDefaultArtifactRepo: false
