apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotlight
  namespace: null-realm
  labels:
    app: spotlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotlight
  template:
    metadata:
      labels:
        app: spotlight
    spec:
      containers:
        - name: spotlight
          image: europe-west1-docker.pkg.dev/helpful-rope-230010/null-realm/spotlight:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://nullrealm:nullrealm_gke_dev@10.5.0.3:5432/nullrealm"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
