apiVersion: v1
kind: Service
metadata:
  name: langfuse
  namespace: null-realm
spec:
  selector:
    app: langfuse
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
